// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import ClickAnswerController from "controllers/click_answer_controller"
application.register("click-answer", ClickAnswerController)

import ColorController from "controllers/color_controller"
application.register("color", ColorController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HoverColorController from "./hover_color_controller"
application.register("hover-color", HoverColorController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import ShareController from "./share_controller"
application.register("share", ShareController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import WordMarkController from "./word_mark_controller"
application.register("word-mark", WordMarkController)
