// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController.js)

import ColorController from "./color_controller"
application.register("color", ColorController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import ShareController from "./share_controller"
application.register("share", ShareController)

import WordMarkController from "./word_mark_controller"
application.register("word-mark", WordMarkController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import ClickAnswerController from "./click_answer_controller"
application.register("click-answer", ClickAnswerController)

import HoverColorController from "./hover_color_controller"
application.register("hover-color", HoverColorController)
